filebeat.inputs:
- type: filestream
    id: my-filestream-id
    enabled: false
    paths:
    - /var/log/*.log
filebeat.config.modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false
setup.template.settings:
  index.number_of_shards: 1
setup.kibana:
output.elasticsearch:
    hosts: ["localhost:9200"]
      preset: balanced
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
processors:
  - drop_event:
      when:
        not:
          suricata.eve.alert.category: Not Suspicious Traffic
          equals:
            suricata.eve.event_type: alert